"""LaTeX macros (\\dg...) for the paper's diagnosis of the per-sample floor
(Reward I, campaign v4): why its tradeoff curve clusters and misses E[c]=tau.

Reads results/v4/frontier_diagnosis/frontier_diagnosis.json
(analysis/frontier_diagnosis.py), results/v4/reward_design/reward_design.json
(analysis/reward_design.py), the 48-prompt probe and the v4 test evals.
Writes paper/tables/diag_numbers.tex and copies the menu figure into the paper.

    python analysis/diagnosis_macros.py
"""
import os, sys, json, shutil, collections
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import full_eval as fe  # noqa: E402
import frontier_diagnosis as fd  # noqa: E402

ROOT = fe.ROOT
A = {"rrebel_l1_std": "Lone", "rrebel_huber_std": "Huber", "grpo_ent": "Gent", "grpo_baseref": "Gbase"}
L = ["% generated by analysis/diagnosis_macros.py -- do not edit by hand"]
FIRST = {}


def m(name, val):
    L.append(f"\\newcommand{{\\dg{name}}}{{{val}}}")


def main():
    D = json.load(open(os.path.join(ROOT, "results/v4/frontier_diagnosis/frontier_diagnosis.json")))["arms"]
    R = json.load(open(os.path.join(ROOT, "results/v4/reward_design/reward_design.json")))
    per, pol = fd.load_probe()
    stats = {p: fd.summarize_prompt(C, S, fd.FINE_TAU) for p, (C, S) in per.items()}
    m("MenuSize", len(per))
    for arm, K in A.items():
        d = D[arm]
        # prompts needed to cover 99% of the (sentence, floor) rows of the eval
        ev = fe.load(fe.path(arm, 12000, 0, camp="v4"))
        cnt = collections.Counter(tuple(p) for row in ev["prompts"] for p in row)
        tot = sum(cnt.values()); acc = 0
        for k, (_, n) in enumerate(cnt.most_common(), 1):
            acc += n
            if acc >= 0.99 * tot:
                break
        m(f"{K}CoverK", k); m(f"{K}PromptsTotal", len(cnt))
        m(f"{K}Switches", len(d["argmax_modal_switch_lambdas"]))
        m(f"{K}RegretMax", f"{max(d['regret_vs_own_menu']):.1f}")
        m(f"{K}ArgmaxRewDiff", f"{d['argmax_vs_sampled']['argmax_reward'] - d['argmax_vs_sampled']['sampled_reward']:+.2f}")
        m(f"{K}ArgmaxHVDiff", f"{d['argmax_vs_sampled']['argmax_hv'] - d['argmax_vs_sampled']['sampled_hv']:+.2f}")
        m(f"{K}FlipExpected", f"{100 * d['expected_flip_independent_draws'][1]:.1f}")
        m(f"{K}PArgmax", f"{d['top1_prob_top3_trunc_median']:.2f}")
        # feasibility of the outgoing / incoming prompt where the reward-optimal
        # LOCATION switches (Lemma "clustering": the switch is set by feasibility)
        P = pol[arm]; q = np.exp(P["lp3"])
        used = [p for j, p in enumerate(P["menu"]) if q[j].mean(1).max() > 0.01 and p in per]
        groups = fd.locations(used, stats)
        gid = {j: gi for gi, g in enumerate(groups) for j in g}
        Rm = np.array([stats[p]["R"] for p in used]); best = Rm.argmax(0)
        outs, ins, first = [], [], None
        for i in range(1, len(best)):
            if gid[best[i]] != gid[best[i - 1]]:
                a_, b_ = stats[used[best[i - 1]]], stats[used[best[i]]]
                outs.append(a_["P"][i]); ins.append(b_["P"][i])
                if first is None and b_["ec"] - a_["ec"] > 15:     # first jump off the positive prompts
                    first = (fd.FINE_TAU[i], a_["P"][i], b_["P"][i], a_["ec"], b_["ec"])
        if arm != "grpo_baseref" and first is not None:
            FIRST[arm] = first
            m(f"{K}FirstSwitchTau", f"{first[0]:.0f}"); m(f"{K}FirstSwitchOut", f"{100 * first[1]:.0f}")
            m(f"{K}FirstSwitchIn", f"{100 * first[2]:.0f}")
        if arm != "grpo_baseref":
            m(f"{K}SwitchOutMin", f"{100 * min(outs):.0f}"); m(f"{K}SwitchOutMax", f"{100 * max(outs):.0f}")
            m(f"{K}SwitchInMin", f"{100 * min(ins):.0f}"); m(f"{K}SwitchInMax", f"{100 * max(ins):.0f}")
    # pooled over the three arms with a clean menu
    outs_all = [float(L_.split("{")[-1].rstrip("}")) for L_ in L if "SwitchOutM" in L_]
    ins_all = [float(L_.split("{")[-1].rstrip("}")) for L_ in L if "SwitchInM" in L_]
    m("SwitchOutLo", f"{min(outs_all):.0f}"); m("SwitchOutHi", f"{max(outs_all):.0f}")
    m("SwitchInLo", f"{min(ins_all):.0f}"); m("SwitchInHi", f"{max(ins_all):.0f}")
    fo = [v[1] for v in FIRST.values()]; fi = [v[2] for v in FIRST.values()]
    m("FirstOutLo", f"{100 * min(fo):.0f}"); m("FirstOutHi", f"{100 * max(fo):.0f}")
    m("FirstInLo", f"{100 * min(fi):.0f}"); m("FirstInHi", f"{100 * max(fi):.0f}")
    m("PeakedArgmaxMaxAbs", f"{max(abs(D[a]['argmax_vs_sampled']['argmax_reward'] - D[a]['argmax_vs_sampled']['sampled_reward']) for a in ('rrebel_l1_std', 'rrebel_huber_std', 'grpo_ent')):.2f}")
    m("RegretGoodMax", f"{max(max(D[a]['regret_vs_own_menu']) for a in ('rrebel_huber_std', 'grpo_ent')):.1f}")
    # per-sample content spread of the prompts the policies use
    sds = [r["within_sd"] for a in A for r in D[a]["content_spread"]]
    m("WithinSDmin", f"{min(sds):.0f}"); m("WithinSDmax", f"{max(sds):.0f}")
    cp = [r["frac_ge99"] for a in A for r in D[a]["content_spread"] if r["ec"] >= 75]
    m("CopyExactMin", f"{100 * min(cp):.0f}"); m("CopyExactMax", f"{100 * max(cp):.0f}")
    # offline comparison of constraint forms (reward_design.json)
    for k, K in (("sample", "Sample"), ("mean", "Mean"), ("mix", "Mix")):
        m(f"Design{K}X", R[k]["x"]["distinct"]); m(f"Design{K}One", R[k]["one"]["distinct"])
    # l1-std late decline (Reward I): the copy prompt takes over ever lower floors
    take, rew50 = {}, {}
    lc = {}
    for st in (4500, 12000):
        ev = fe.load(fe.path("rrebel_l1_std", st, 0, camp="v4"))
        pr = [[tuple(p) for p in row] for row in ev["prompts"]]
        acc_ = collections.defaultdict(list)
        for a in range(20):
            for b in range(len(pr[a])):
                acc_[pr[a][b]].append(ev["content"][a, b])
        pc = {p: np.mean(v) for p, v in acc_.items()}
        share = [np.mean([pc[p] >= 75 for p in pr[a]]) for a in range(20)]
        take[st] = next(5 * a for a in range(20) if share[a] >= 0.5)
        rew50[st] = ev["score"][10].mean()
        lc[st] = ev["score"].mean(1)
    m("LoneTakeoverPeak", take[4500]); m("LoneTakeoverEnd", take[12000])
    m("LoneRewFiftyPeak", f"{rew50[4500]:.1f}"); m("LoneRewFiftyEnd", f"{rew50[12000]:.1f}")
    drop = (lc[4500] - lc[12000]) / 20                      # contribution of each floor to the mean
    m("LoneDropMid", f"{drop[8:15].sum():.1f}"); m("LoneDropAll", f"{drop.sum():.1f}")
    # l1-std's copy prompt and its best mid-content prompt (pooled means)
    mu_ = sorted(D["rrebel_l1_std"]["menu_used"], key=lambda r: r["ec"])
    copy = mu_[-1]; mid = max((r for r in mu_ if 40 < r["ec"] < 75), key=lambda r: r["es"])
    m("LoneCopyC", f"{copy['ec']:.0f}"); m("LoneCopyS", f"{copy['es']:.0f}")
    m("LoneMidC", f"{mid['ec']:.0f}"); m("LoneMidS", f"{mid['es']:.0f}")
    out = os.path.join(fe.TAB, "diag_numbers.tex")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"wrote {len(L) - 1} macros -> {out}")
    for f in ("menu_mechanism.pdf", "menu_mechanism.png"):
        shutil.copy(os.path.join(ROOT, "results/v4/frontier_diagnosis", f), os.path.join(fe.FIG, f))
    print("copied menu_mechanism -> paper/figures")


if __name__ == "__main__":
    main()
