"""Paper tables from analysis/example_outputs.py:

  paper/tables/example.tex   one input sentence, the prompt Huber-std emits at
                             five floors under each reward, and what the task
                             model writes with it
  paper/tables/outcomes.tex  what individual rewrites look like at the binding
                             floors, over 100 test sentences (if the audit ran)
  paper/tables/example_numbers.tex  \\ex... macros

Rewrites at a floor are bimodal in sentiment (classifier probabilities near 0 or
100), so a single "typical" rewrite would mislead. Each floor therefore shows the
share of positive rewrites (s >= 50) and one rewrite from each group: the one
with the group's median content (not the best one).

    python analysis/example_table.py
"""
import os, sys, json
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import full_eval as fe  # noqa: E402

ROOT = fe.ROOT
EX = os.path.join(ROOT, "results", "examples")
POS = 50.0
L = ["% generated by analysis/example_table.py -- do not edit by hand"]


def m(name, val):
    L.append(f"\\newcommand{{\\ex{name}}}{{{val}}}")


def median_member(samples):
    if not samples:
        return None
    cs = np.array([x["content"] for x in samples])
    return samples[int(np.argmin(np.abs(cs - np.median(cs))))]


def cell(x):
    if x is None:
        return "---"
    return (f"{fe.tex_escape(x['text'])} "
            f"{{\\normalfont\\tiny($c{{=}}{x['content']:.0f}$, $s{{=}}{x['sentiment']:.0f}$)}}")


def example_table(src_index=403):
    rows, source = [], None
    for camp, title in (("v5", "Reward~II (floor on expected content)"),
                        ("v4", "Reward~I (floor on every sample)")):
        d = json.load(open(os.path.join(EX, f"{camp}_rrebel_huber_std_seed0.json")))
        ex = next(e for e in d["examples"] if e["src_index"] == src_index)
        source = ex["source"]
        rows.append(f"\\multicolumn{{6}}{{l}}{{\\normalfont\\small\\emph{{{title}}}}} \\\\[1pt]")
        for f in ex["floors"]:
            pos = [x for x in f["samples"] if x["sentiment"] >= POS]
            neg = [x for x in f["samples"] if x["sentiment"] < POS]
            rows.append(f"${f['tau']}$ & {fe.breakable(fe.tex_escape(f['prompt'].strip()))} & "
                        f"${f['mean_content']:.0f}$ / ${f['mean_sentiment']:.0f}$ & "
                        f"${100 * len(pos) / len(f['samples']):.0f}\\%$ & "
                        f"{cell(median_member(pos))} & {cell(median_member(neg))} \\\\")
            print(f"{camp} tau={f['tau']:2d} {f['prompt'].strip()!r:44s} E[c]={f['mean_content']:5.1f} "
                  f"E[s]={f['mean_sentiment']:5.1f} pos={100 * len(pos) / len(f['samples']):3.0f}%  "
                  f"+ {median_member(pos)['text'] if pos else '-'!r}  | - {median_member(neg)['text'] if neg else '-'!r}")
        rows.append("\\midrule")
    rows = rows[:-1]
    col = ">{\\raggedright\\arraybackslash\\scriptsize}p{%s}"
    with open(os.path.join(fe.TAB, "example.tex"), "w") as fh:
        fh.write("% generated by analysis/example_table.py -- do not edit by hand\n")
        fh.write("\\begin{tabular}{r" + (">{\\raggedright\\arraybackslash\\ttfamily\\scriptsize}p{0.19\\textwidth}")
                 + "cc" + col % "0.255\\textwidth" + col % "0.255\\textwidth" + "}\n\\toprule\n")
        fh.write(f"\\multicolumn{{6}}{{l}}{{\\normalfont\\small Input: \\emph{{{fe.tex_escape(source)}}}}} \\\\\n\\midrule\n")
        fh.write("$\\tau$ & \\normalfont\\small Prompt & $\\mathbb{E}[c]$ / $\\mathbb{E}[s]$ & Positive & "
                 "A positive rewrite & A non-positive rewrite \\\\\n\\midrule\n")
        fh.write("\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    m("SrcIndex", src_index)
    print("wrote", os.path.join(fe.TAB, "example.tex"))


def outcomes_table():
    runs = [("v5", "rrebel_huber_std"), ("v4", "rrebel_huber_std"), ("v5", "rrebel_l1_std"), ("v4", "rrebel_l1_std")]
    have = [r for r in runs if os.path.exists(os.path.join(EX, f"outcomes_{r[0]}_{r[1]}_seed0.json"))]
    if len(have) < len(runs):
        print("outcome audit incomplete; skipping outcomes.tex"); return
    out_rows = []
    for camp, arm in runs:
        d = json.load(open(os.path.join(EX, f"outcomes_{camp}_{arm}_seed0.json")))
        byt = {}
        for e in d["examples"]:
            for f in e["floors"]:
                c = np.array([x["content"] for x in f["samples"]]); s = np.array([x["sentiment"] for x in f["samples"]])
                t = f["tau"]
                byt.setdefault(t, []).append([np.mean((s >= POS) & (c >= t)),          # success: positive AND meets the floor
                                              np.mean((s >= POS) & (c < t)),           # positive but drifted below the floor
                                              np.mean((s < POS) & (c >= 95)),          # (near-)copy, not positive
                                              np.mean((s < POS) & (c < 95))])          # other
        n = len(d["examples"])
        tag = ("Five" if camp == "v5" else "Four") + fe.MACRO_ARM[arm]
        cells = []
        for t in sorted(byt):
            v = 100 * np.mean(byt[t], 0)
            cells.append(v)
            word = {30: "AtThirty", 50: "AtFifty", 70: "AtSeventy"}[t]     # TeX names: letters only
            for k, K in enumerate(("Success", "Drift", "Copy", "Other")):
                m(f"{tag}{K}{word}", f"{v[k]:.0f}")
        avg = 100 * np.mean([np.mean(byt[t], 0) for t in byt], 0)
        for k, K in enumerate(("Success", "Drift", "Copy", "Other")):
            m(f"{tag}{K}", f"{avg[k]:.0f}")
        label = ("Reward~II" if camp == "v5" else "Reward~I") + ", " + fe.SHORT[arm]
        out_rows.append(f"{label} & " + " & ".join(
            f"${v[0]:.0f}$ / ${v[1]:.0f}$ / ${v[2]:.0f}$" for v in cells) + f" & ${avg[0]:.0f}$ \\\\")
        print(f"{camp} {arm}: n={n} " + "  ".join(f"tau{t}: succ {100*np.mean(byt[t],0)[0]:.0f} drift {100*np.mean(byt[t],0)[1]:.0f} "
                                                  f"copy {100*np.mean(byt[t],0)[2]:.0f}" for t in sorted(byt)))
    m("AuditN", n)
    with open(os.path.join(fe.TAB, "outcomes.tex"), "w") as fh:
        fh.write("% generated by analysis/example_table.py -- do not edit by hand\n")
        fh.write("\\begin{tabular}{lcccc}\n\\toprule\n & $\\tau = 30$ & $\\tau = 50$ & $\\tau = 70$ & Success \\\\\n"
                 " & \\multicolumn{3}{c}{success / drift / copy (\\% of rewrites)} & (mean) \\\\\n\\midrule\n")
        fh.write("\n".join(out_rows) + "\n\\bottomrule\n\\end{tabular}\n")
    print("wrote", os.path.join(fe.TAB, "outcomes.tex"))


if __name__ == "__main__":
    example_table()
    outcomes_table()
    open(os.path.join(fe.TAB, "example_numbers.tex"), "w").write("\n".join(L) + "\n")
    print(f"wrote {len(L) - 1} macros -> {os.path.join(fe.TAB, 'example_numbers.tex')}")
