"""Reward-scale probe -> evidence for the R-REBEL-std theory (paper Sec. 5.2).

Reads results/v4/reward_scale_probe/*.json (analysis/reward_scale_probe.py):
per (test source x, lambda) group, the G=16 Monte-Carlo rewards of prompts
drawn by the TRAINING sampler. For each group it computes

  sigma_hat           the in-group std, i.e. what R-REBEL-std divides by;
  KL radius (plain)   KL(target || group) for the plain target  pi0 e^{r/beta};
  KL radius (std)     KL(target || group) for the std target    pi0 e^{r/(beta sigma_hat)};

using the group's own empirical distribution as pi0 (plug-in; Prop. 2). The
plug-in KL is at most log G = 2.77 nats (the target is a point mass).

    python analysis/reward_scale_analysis.py
"""
import glob, json, os, re
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BETA = 0.5
BLUE, ORANGE, INK2, GRID = "#2a78d6", "#eb6834", "#52514e", "#e4e3df"


def plugin_kl(r, t):
    lw = t * (r - r.max())
    p = np.exp(lw); p /= p.sum()
    nz = p > 0
    return float(np.sum(p[nz] * np.log(p[nz] * len(r))))


def main():
    files = sorted(glob.glob(os.path.join(ROOT, "results/v4/reward_scale_probe/*.json")),
                   key=lambda f: int(re.search(r"step(\d+)", f).group(1)))
    if not files:
        raise SystemExit("no probe outputs yet")
    summary = {}
    per_step = {}
    for f in files:
        step = int(re.search(r"step(\d+)", f).group(1))
        d = json.load(open(f))
        G = d["G"]
        rows = []
        for g in d["groups"]:
            r = np.array(g["reward"], dtype=float)
            sd = r.std(ddof=1)
            if sd <= 0:
                rows.append((g["lmbda"], 0.0, np.nan, np.nan)); continue
            rows.append((g["lmbda"], sd, plugin_kl(r, 1 / BETA), plugin_kl(r, 1 / (BETA * sd))))
        a = np.array(rows)
        lam, sd, klp, kls = a.T
        ok = sd > 0
        by_tau = {}
        for l in sorted(set(lam)):
            m = (lam == l) & ok
            by_tau[f"{100 * l:g}"] = {
                "n": int(((lam == l)).sum()), "n_degenerate": int(((lam == l) & ~ok).sum()),
                "sigma_q": np.percentile(sd[m], [5, 25, 50, 75, 95]).tolist() if m.any() else None}
        s = {
            "groups": int(len(a)), "degenerate_frac": float((~ok).mean()),
            "sigma_q05_q50_q95": np.percentile(sd[ok], [5, 50, 95]).tolist(),
            "sigma_range_q95_over_q05": float(np.percentile(sd[ok], 95) / np.percentile(sd[ok], 5)),
            "sigma_range_max_over_min": float(sd[ok].max() / sd[ok].min()),
            "kl_plain_q05_q50_q95": np.percentile(klp[ok], [5, 50, 95]).tolist(),
            "kl_std_q05_q50_q95": np.percentile(kls[ok], [5, 50, 95]).tolist(),
            "kl_plain_frac_below_0.01": float((klp[ok] < 0.01).mean()),
            "kl_plain_frac_above_2.5": float((klp[ok] > 2.5).mean()),
            "kl_std_frac_below_0.01": float((kls[ok] < 0.01).mean()),
            "kl_std_frac_above_2.5": float((kls[ok] > 2.5).mean()),
            "by_tau": by_tau,
            "log_G": float(np.log(G)),
        }
        summary[step] = s
        per_step[step] = (lam, sd, klp, kls, ok)
        print(f"\n=== step {step}: {s['groups']} groups, degenerate (all rewards tied) {s['degenerate_frac']:.1%}")
        print(f"  sigma_hat  q05/q50/q95 = {np.round(s['sigma_q05_q50_q95'], 4)}   q95/q05 = {s['sigma_range_q95_over_q05']:.0f}x   max/min = {s['sigma_range_max_over_min']:.2e}")
        print(f"  KL plain   q05/q50/q95 = {np.round(s['kl_plain_q05_q50_q95'], 4)}   <0.01: {s['kl_plain_frac_below_0.01']:.1%}   >2.5: {s['kl_plain_frac_above_2.5']:.1%}")
        print(f"  KL std     q05/q50/q95 = {np.round(s['kl_std_q05_q50_q95'], 4)}   <0.01: {s['kl_std_frac_below_0.01']:.1%}   >2.5: {s['kl_std_frac_above_2.5']:.1%}")
        for t, v in by_tau.items():
            q = v["sigma_q"]
            print(f"    tau={t:>3s}: median sigma {q[2] if q else float('nan'):9.4f}  IQR [{q[1] if q else 0:.4f}, {q[3] if q else 0:.4f}]  degenerate {v['n_degenerate']}/{v['n']}")
    json.dump(summary, open(os.path.join(ROOT, "results/v4/reward_scale_summary.json"), "w"), indent=1)

    # macros for the paper (ranges across all probed checkpoints)
    steps = sorted(summary)
    fin = steps[-1]
    BS = chr(92)

    def pct(x):
        return f"{100 * x:.0f}" + BS + "%"

    def rng(key, f=lambda x: f"{x:.0f}"):
        vals = [summary[st][key] for st in steps]
        lo, hi = f(min(vals)), f(max(vals))
        return lo if lo == hi else lo + "--" + hi

    def mac(name, val):
        return BS + "newcommand{" + BS + name + "}{" + str(val) + "}"

    med = {t: v["sigma_q"][2] for t, v in summary[fin]["by_tau"].items() if v["sigma_q"]}
    std_med = [summary[st]["kl_std_q05_q50_q95"][1] for st in steps]
    L = ["% generated by analysis/reward_scale_analysis.py -- do not edit by hand",
         mac("sProbeSteps", ", ".join(str(st) for st in steps)),
         mac("sProbeFinal", fin),
         mac("sGroups", summary[fin]["groups"]),
         mac("sRangeQ", rng("sigma_range_q95_over_q05")),
         mac("sPlainStuck", rng("kl_plain_frac_below_0.01", pct)),
         mac("sPlainCollapse", rng("kl_plain_frac_above_2.5", pct)),
         mac("sStdStuck", rng("kl_std_frac_below_0.01", pct)),
         mac("sStdCollapse", rng("kl_std_frac_above_2.5", pct)),
         mac("sStdMedKL", f"{min(std_med):.1f}--{max(std_med):.1f}"),
         mac("sSigZeroFin", f"{med['0']:.1f}"),
         mac("sSigMaxFin", f"{max(med.values()):.1f}"),
         mac("sSigNinetyFin", f"{med['90']:.2f}"),
         mac("sTauRatioFin", f"{max(med.values()) / min(med.values()):.0f}"),
         mac("sLogG", f"{summary[fin]['log_G']:.2f}")]
    open(os.path.join(ROOT, "paper/tables/scale_numbers.tex"), "w").write("\n".join(L) + "\n")
    print("wrote paper/tables/scale_numbers.tex")

    import matplotlib; matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.size": 8, "xtick.labelsize": 7, "ytick.labelsize": 7})
    final = max(per_step)
    lam, sd, klp, kls, ok = per_step[final]
    fig, ax = plt.subplots(1, 2, figsize=(6.6, 2.55))  # print size
    taus = sorted(set(lam))
    data = [sd[(lam == l) & ok] for l in taus]
    bp = ax[0].boxplot(data, positions=[100 * l for l in taus], widths=5, whis=(5, 95),
                       showfliers=False, patch_artist=True, medianprops=dict(color="#0b0b0b", lw=1.2))
    for b in bp["boxes"]:
        b.set(facecolor=BLUE, alpha=0.35, edgecolor=BLUE)
    for k in ("whiskers", "caps"):
        for w in bp[k]:
            w.set(color=BLUE)
    ax[0].set_yscale("log"); ax[0].set_xlabel(r"content floor $\tau=100\lambda$")
    ax[0].set_ylabel(r"in-group reward std $\hat\sigma(x,\lambda)$")
    ax[0].set_xticks([100 * l for l in taus]); ax[0].set_xticklabels([f"{100 * l:g}" for l in taus], fontsize=6.5)
    ax[0].set_title(f"reward scale across contexts (step {final})", fontsize=8.5)
    bins = np.logspace(-6, np.log10(3), 50)
    ax[1].hist(np.clip(klp[ok], 1e-6, None), bins=bins, color=ORANGE, alpha=0.6, label=r"plain target $e^{r/\beta}$")
    ax[1].hist(np.clip(kls[ok], 1e-6, None), bins=bins, color=BLUE, alpha=0.6, label=r"std target $e^{r/(\beta\hat\sigma)}$")
    ax[1].axvline(np.log(16), color=INK2, ls=":", lw=1); ax[1].text(np.log(16), ax[1].get_ylim()[1] * 0.9, " point\n mass", fontsize=7, color=INK2, va="top")
    ax[1].set_xscale("log"); ax[1].set_xlabel("one-window KL radius, plug-in [nats]"); ax[1].set_ylabel("groups")
    ax[1].set_title("trust-region radius per context", fontsize=8.5); ax[1].legend(frameon=False, fontsize=6.5, loc="upper left")
    for a in ax:
        a.spines[["top", "right"]].set_visible(False); a.grid(True, color=GRID, lw=0.6); a.set_axisbelow(True)
    fig.tight_layout()
    out = os.path.join(ROOT, "paper/figures/reward_scale.pdf")
    fig.savefig(out); fig.savefig(out.replace(".pdf", ".png"), dpi=120)
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
